name: fwf
description: Maihama Food Guide App
version: 0.0.1-dev

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  json_serializable: ^6.9.4
  riverpod_annotation: ^2.6.1
  yaml: ^3.1.3
  flutter_sticky_header: ^0.7.0
  flutter_custom_tabs: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.4
  freezed: ^3.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/
